/**
 * Enaplo
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.ocist.enaplo.login.data.requests


import com.squareup.moshi.Json

/**
 * 
 *
 * @param lessonId 
 * @param dividendId 
 * @param date 
 * @param studentIds 
 */

data class MissingStudentsRequest (

    @Json(name = "lessonId")
    val lessonId: kotlin.Int? = null,

    @Json(name = "dividendId")
    val dividendId: kotlin.Int? = null,

    @Json(name = "date")
    val date: java.time.OffsetDateTime? = null,

    @Json(name = "studentIds")
    val studentIds: kotlin.collections.List<kotlin.Int>? = null

)

